server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA: redirigir todo al index para el router
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Evitar cachear index.html para que siempre se sirva la versión más reciente
    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires 0;
    }
}
