# =============================================
# SonarQube – tienda-front (Angular)
# =============================================

sonar.projectKey=tienda-front
sonar.projectName=Tienda Front - Angular
sonar.projectVersion=1.0

# Código fuente
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/node_modules/**,**/*.d.ts,src/main.ts,src/styles.scss

# Tests
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Cobertura (lcov generado por karma-coverage)
sonar.javascript.lcov.reportPaths=coverage/tienda-front/lcov.info

# TypeScript
sonar.typescript.tsconfigPath=tsconfig.app.json
sonar.sourceEncoding=UTF-8

# Servidor SonarQube local
sonar.host.url=http://localhost:9000
sonar.token=sqa_06dcaacc13b49229439d1dd1e391bc4ed32c59a8
